### PR TITLE
Update .bashrc kitty-completion example.

### PR DESCRIPTION
**Pull request by sterpe**
See https://github.com/kovidgoyal/kitty/issues/1520

### CODE REVIEW

**Comment by Luflosi** [comment]
You should make this pull request in the kitty repo, in the file `docs/index.rst`.

**Comment by Luflosi** [comment]
And in case you didn't know, you can also force-push a branch instead of making a new pull-request.

**Comment by sterpe** [comment]
Thanks, I've been working in `hg` mostly and it's a bit different.

**Comment by sterpe** [comment]
Closing PR here in favor of https://github.com/kovidgoyal/kitty/pull/1800

**Pull request closed without merging**
